# Generated by Django 5.2.7 on 2025-11-02 06:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this record is active",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the category",
                        max_length=100,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the category",
                        verbose_name="description",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon identifier (e.g., Font Awesome class)",
                        max_length=50,
                        verbose_name="icon",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Hex color code for the category",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Color must be a valid hex color code (e.g., #FF5733)",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                        verbose_name="color",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in which the category should appear",
                        verbose_name="sort order",
                    ),
                ),
                (
                    "budget_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional budget limit for this category",
                        max_digits=12,
                        null=True,
                        verbose_name="budget limit",
                    ),
                ),
                (
                    "is_essential",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this expense category is essential (vs discretionary)",
                        verbose_name="is essential",
                    ),
                ),
                (
                    "allows_split",
                    models.BooleanField(
                        default=True,
                        help_text="Whether expenses in this category can be split across multiple categories",
                        verbose_name="allows split",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category for creating hierarchies",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="categories.expensecategory",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Category",
                "verbose_name_plural": "Expense Categories",
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["name", "is_active"], name="categories__name_9e72a7_idx"
                    ),
                    models.Index(
                        fields=["created_by", "is_active"],
                        name="categories__created_77ab3b_idx",
                    ),
                    models.Index(
                        fields=["is_essential", "is_active"],
                        name="categories__is_esse_545aff_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "parent"),
                        name="unique_expense_category_name_parent",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="IncomeCategory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this record is active",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the category",
                        max_length=100,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the category",
                        verbose_name="description",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon identifier (e.g., Font Awesome class)",
                        max_length=50,
                        verbose_name="icon",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Hex color code for the category",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Color must be a valid hex color code (e.g., #FF5733)",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                        verbose_name="color",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in which the category should appear",
                        verbose_name="sort order",
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this income type is typically recurring",
                        verbose_name="is recurring",
                    ),
                ),
                (
                    "tax_applicable",
                    models.BooleanField(
                        default=False,
                        help_text="Whether income from this category is taxable",
                        verbose_name="tax applicable",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category for creating hierarchies",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="categories.incomecategory",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Income Category",
                "verbose_name_plural": "Income Categories",
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["name", "is_active"], name="categories__name_76ffd7_idx"
                    ),
                    models.Index(
                        fields=["created_by", "is_active"],
                        name="categories__created_337917_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "parent"),
                        name="unique_income_category_name_parent",
                    )
                ],
            },
        ),
    ]
