# Generated by Django 5.2.7 on 2025-11-02 06:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Soft delete flag"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        help_text="Transaction amount",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="amount",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description or notes about the transaction",
                        verbose_name="description",
                    ),
                ),
                (
                    "transaction_date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Date when the transaction occurred",
                        verbose_name="transaction date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="COMPLETED",
                        help_text="Current status of the transaction",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="External reference number (e.g., invoice number)",
                        max_length=100,
                        verbose_name="reference number",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata for the transaction",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags for categorizing and searching",
                        verbose_name="tags",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CREDIT_CARD", "Credit Card"),
                            ("DEBIT_CARD", "Debit Card"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("MOBILE_PAYMENT", "Mobile Payment"),
                            ("CHECK", "Check"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="CASH",
                        help_text="Method used for payment",
                        max_length=20,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        blank=True,
                        help_text="Vendor or merchant name",
                        max_length=200,
                        verbose_name="vendor",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Location where the expense occurred",
                        max_length=200,
                        verbose_name="location",
                    ),
                ),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        help_text="Receipt image or file",
                        null=True,
                        upload_to="receipts/%Y/%m/",
                        verbose_name="receipt",
                    ),
                ),
                (
                    "is_reimbursable",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this expense is reimbursable",
                        verbose_name="is reimbursable",
                    ),
                ),
                (
                    "reimbursed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this expense has been reimbursed",
                        verbose_name="reimbursed",
                    ),
                ),
                (
                    "reimbursement_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when the expense was reimbursed",
                        null=True,
                        verbose_name="reimbursement date",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Expense category",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="categories.expensecategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expense Entries",
                "ordering": ["-transaction_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "transaction_date"],
                        name="transaction_categor_88fc12_idx",
                    ),
                    models.Index(
                        fields=["payment_method", "transaction_date"],
                        name="transaction_payment_50d39a_idx",
                    ),
                    models.Index(
                        fields=["vendor", "transaction_date"],
                        name="transaction_vendor_2b5bee_idx",
                    ),
                    models.Index(
                        fields=["is_reimbursable", "reimbursed"],
                        name="transaction_is_reim_bb992f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Soft delete flag"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        help_text="Transaction amount",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="amount",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description or notes about the transaction",
                        verbose_name="description",
                    ),
                ),
                (
                    "transaction_date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Date when the transaction occurred",
                        verbose_name="transaction date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="COMPLETED",
                        help_text="Current status of the transaction",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="External reference number (e.g., invoice number)",
                        max_length=100,
                        verbose_name="reference number",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata for the transaction",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags for categorizing and searching",
                        verbose_name="tags",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Source of income (e.g., employer name, client name)",
                        max_length=200,
                        verbose_name="source",
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a recurring income",
                        verbose_name="is recurring",
                    ),
                ),
                (
                    "recurrence_period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("BIWEEKLY", "Bi-weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUALLY", "Annually"),
                        ],
                        help_text="Frequency of recurring income",
                        max_length=20,
                        null=True,
                        verbose_name="recurrence period",
                    ),
                ),
                (
                    "next_occurrence",
                    models.DateField(
                        blank=True,
                        help_text="Next expected occurrence date for recurring income",
                        null=True,
                        verbose_name="next occurrence",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Tax deducted from this income",
                        max_digits=12,
                        verbose_name="tax amount",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Income category",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="categories.incomecategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Income",
                "verbose_name_plural": "Income Entries",
                "ordering": ["-transaction_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "transaction_date"],
                        name="transaction_categor_3c1d69_idx",
                    ),
                    models.Index(
                        fields=["source", "transaction_date"],
                        name="transaction_source_7255b3_idx",
                    ),
                    models.Index(
                        fields=["is_recurring", "next_occurrence"],
                        name="transaction_is_recu_ed55f7_idx",
                    ),
                ],
            },
        ),
    ]
