# Generated by Django 5.2.7 on 2025-11-05 12:08

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Soft delete flag"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for the budget",
                        max_length=200,
                        verbose_name="budget name",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total budget amount for the period",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="budget amount",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("YEARLY", "Yearly"),
                            ("CUSTOM", "Custom Period"),
                        ],
                        default="MONTHLY",
                        help_text="Budget period type",
                        max_length=20,
                        verbose_name="period",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Budget period start date", verbose_name="start date"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="Budget period end date", verbose_name="end date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("EXCEEDED", "Exceeded"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="ACTIVE",
                        help_text="Current status of the budget",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "alert_threshold_80",
                    models.BooleanField(
                        default=True,
                        help_text="Send alert when 80% of budget is used",
                        verbose_name="alert at 80%",
                    ),
                ),
                (
                    "alert_threshold_100",
                    models.BooleanField(
                        default=True,
                        help_text="Send alert when budget is exceeded",
                        verbose_name="alert at 100%",
                    ),
                ),
                (
                    "alerted_at_80",
                    models.BooleanField(
                        default=False,
                        help_text="Whether 80% alert has been sent",
                        verbose_name="80% alert sent",
                    ),
                ),
                (
                    "alerted_at_100",
                    models.BooleanField(
                        default=False,
                        help_text="Whether 100% alert has been sent",
                        verbose_name="100% alert sent",
                    ),
                ),
                (
                    "rollover_unused",
                    models.BooleanField(
                        default=False,
                        help_text="Roll over unused budget to next period",
                        verbose_name="rollover unused amount",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the budget",
                        verbose_name="notes",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Expense category for this budget",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="categories.expensecategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this budget",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget",
                "verbose_name_plural": "Budgets",
                "ordering": ["-start_date", "category"],
            },
        ),
        migrations.CreateModel(
            name="BudgetAlert",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("80_PERCENT", "80% Threshold"),
                            ("EXCEEDED", "Budget Exceeded"),
                            ("CUSTOM", "Custom Alert"),
                        ],
                        help_text="Type of alert",
                        max_length=20,
                        verbose_name="alert type",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Alert message content", verbose_name="message"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the alert has been read",
                        verbose_name="is read",
                    ),
                ),
                (
                    "sent_via_email",
                    models.BooleanField(
                        default=False,
                        help_text="Whether alert was sent via email",
                        verbose_name="sent via email",
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        help_text="Related budget",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="budgets.budget",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who received the alert",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget Alert",
                "verbose_name_plural": "Budget Alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["user", "status"], name="budgets_bud_user_id_60f731_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["start_date", "end_date"], name="budgets_bud_start_d_b133e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["category", "start_date"], name="budgets_bud_categor_34ff6d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="budget",
            unique_together={("user", "category", "start_date", "end_date")},
        ),
        migrations.AddIndex(
            model_name="budgetalert",
            index=models.Index(
                fields=["user", "is_read"], name="budgets_bud_user_id_748b65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budgetalert",
            index=models.Index(
                fields=["budget", "alert_type"], name="budgets_bud_budget__2b2c7c_idx"
            ),
        ),
    ]
