# Generated by Django 5.2.7 on 2025-11-05 12:08

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Debt",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Soft delete flag"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount owed",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="amount",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of the debt", verbose_name="description"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PARTIALLY_PAID", "Partially Paid"),
                            ("SETTLED", "Settled"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        help_text="Current status of the debt",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="Due date for payment",
                        null=True,
                        verbose_name="due date",
                    ),
                ),
                (
                    "settled_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount already paid",
                        max_digits=12,
                        verbose_name="settled amount",
                    ),
                ),
                (
                    "settled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the debt was fully settled",
                        null=True,
                        verbose_name="settled at",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creditor",
                    models.ForeignKey(
                        help_text="User who is owed money",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="debts_owed_to_me",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "debtor",
                    models.ForeignKey(
                        help_text="User who owes money",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="my_debts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Debt",
                "verbose_name_plural": "Debts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DebtPayment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="amount",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        default="CASH",
                        help_text="Payment method used",
                        max_length=50,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Payment reference number",
                        max_length=100,
                        verbose_name="reference number",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Payment notes", verbose_name="notes"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "debt",
                    models.ForeignKey(
                        help_text="Related debt",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="shared_expenses.debt",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Debt Payment",
                "verbose_name_plural": "Debt Payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseGroup",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Soft delete flag"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the expense group",
                        max_length=200,
                        verbose_name="group name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the group",
                        verbose_name="description",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-users",
                        help_text="Font Awesome icon class",
                        max_length=50,
                        verbose_name="icon",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Group color (hex code)",
                        max_length=7,
                        verbose_name="color",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the group is active",
                        verbose_name="is active",
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        help_text="Administrator of the group",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="administered_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        help_text="Members of this group",
                        related_name="expense_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Group",
                "verbose_name_plural": "Expense Groups",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="debt",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Related expense group (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="debts",
                to="shared_expenses.expensegroup",
            ),
        ),
        migrations.CreateModel(
            name="SharedExpense",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Soft delete flag"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "split_method",
                    models.CharField(
                        choices=[
                            ("EQUAL", "Equal Split"),
                            ("EXACT", "Exact Amounts"),
                            ("PERCENTAGE", "By Percentage"),
                            ("SHARES", "By Shares"),
                        ],
                        default="EQUAL",
                        help_text="Method used to split the expense",
                        max_length=20,
                        verbose_name="split method",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the split",
                        verbose_name="notes",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        help_text="Related expense transaction",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_info",
                        to="transactions.expense",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Expense group",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_expenses",
                        to="shared_expenses.expensegroup",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        help_text="User who paid for the expense",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shared_expenses_paid",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Shared Expense",
                "verbose_name_plural": "Shared Expenses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SharedExpenseSplit",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount owed by this user",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="amount",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage of total (if split by percentage)",
                        max_digits=5,
                        null=True,
                        verbose_name="percentage",
                    ),
                ),
                (
                    "is_settled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this split has been settled",
                        verbose_name="is settled",
                    ),
                ),
                (
                    "settled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this split was settled",
                        null=True,
                        verbose_name="settled at",
                    ),
                ),
                (
                    "settlement_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about the settlement",
                        verbose_name="settlement notes",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_expense",
                    models.ForeignKey(
                        help_text="Related shared expense",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="splits",
                        to="shared_expenses.sharedexpense",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User responsible for this split",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expense_splits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Split",
                "verbose_name_plural": "Expense Splits",
                "ordering": ["-created_at"],
                "unique_together": {("shared_expense", "user")},
            },
        ),
        migrations.AddField(
            model_name="debt",
            name="shared_expense_split",
            field=models.ForeignKey(
                blank=True,
                help_text="Related expense split (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="debt",
                to="shared_expenses.sharedexpensesplit",
            ),
        ),
        migrations.AddIndex(
            model_name="debt",
            index=models.Index(
                fields=["creditor", "status"], name="shared_expe_credito_65b52f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="debt",
            index=models.Index(
                fields=["debtor", "status"], name="shared_expe_debtor__32d307_idx"
            ),
        ),
    ]
